
1. Dodaj logowanie przez formularz ładując usera z fixturek.
2. Aktualizuj hasło Usera z automatu (pole plainPassword).
3. Zrób Voter określający czy można dodawać komentarze do artykułu.
4. Dodaj rejestrację przez formularz z wysyłką maila rejestracyjnego.
