#index:
#    path: /
#    controller: App\Controller\DefaultController::index


about:
    path: /about
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
       template: about/index.html.twig
